name: "Reusable Format PR Workflow"

on:
  workflow_call:

jobs:
  check-typos:
    name: "Check Typos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@v1.16.23 
        with: 
          write_changes: true